Repository essence-community/core-frontend, pull requests merged in 2020-06, with the labels that each got.

#384 CORE-1782 inversed editing field for hidden
  packages/@essence/essence-constructor-classes/src/Window/utils/getWindowChilds.ts
Labels: bug

#385 CORE-1782 add child if editmode = undefined
  packages/@essence/essence-constructor-classes/src/Window/utils/getWindowChilds.ts
Labels: bug

#386 Core 1787
  docs/ATTRIBUTES.md
  packages/@essence/essence-constructor-classes/src/AppBar/container/AppBar.tsx
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/getThemeOverridesDefault.ts
  packages/@essence/essence-constructor-classes/src/Box/containers/BoxContainer.tsx
  packages/@essence/essence-constructor-classes/src/Button/store/FileInputModel.ts
  packages/@essence/essence-constructor-classes/src/EmptySpace/container/EmptySpace.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/store/FieldComboModel.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/FieldCssMeasure.types.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/components/NumberFormat/NumberFormat.tsx
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/components/NumberFormat/index.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/constants.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/containers/FieldCssMeasureContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/containers/FieldCssMeasureContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/index.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/utils/index.ts
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/utils/parseValue.ts
  packages/@essence/essence-constructor-classes/src/FieldGroup/containers/FieldGroupContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldImage/containers/FieldImageContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldAddrConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldMoConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldRadio/containers/FieldRadioContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/FieldTextarea/components/FieldTextareaInput.tsx
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelModelBtnConfigs.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridHeight.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/printExcel.ts
  packages/@essence/essence-constructor-classes/src/Iframe/containers/IframeContainer.tsx
  packages/@essence/essence-constructor-classes/src/OpenPageTabs/container/OpenPageTabs.tsx
  packages/@essence/essence-constructor-classes/src/PanelDynamic/containers/PanelDynamicContainer.tsx
  packages/@essence/essence-constructor-classes/src/RoadMap/companents/RoadMapTab/RoadMapTab.tsx
  packages/@essence/essence-constructor-classes/src/ToolBar/container/ToolBar.tsx
  packages/@essence/essence-constructor-classes/src/Window/containers/WindowContainer.tsx
  packages/@essence/essence-constructor-classes/src/WindowDrawer/containers/WindowDrawerContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/WindowDrawer/containers/WindowDrawerContainer.tsx
  packages/@essence/essence-constructor-share/scripts/update.js
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/loadRecordsAction.ts
  packages/@essence/essence-constructor-share/src/request/request.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/types/Request.ts
  packages/@essence/essence-constructor-share/src/uicomponents/Popover/Popover.types.ts
  packages/@essence/essence-constructor-share/src/utils/bignumber.ts
  packages/@essence/essence-constructor-share/src/utils/download.ts
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-share/src/utils/validations.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: enhancement

#387 CORE-1787 fixed hidden child for editmode
  packages/@essence/essence-constructor-classes/src/Window/utils/getWindowChilds.ts
Labels: bug

#388 CORE-1788 wait for init globals in the application, removed g_sys_fro…
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-share/src/constants/variables.ts
  packages/@essence/essence-constructor-website/src/Components/Settings/Settings.tsx
Labels: bug

#392 Core 1791
  docs/ATTRIBUTES.md
  packages/@essence/essence-constructor-classes/scripts/fetchTypes.js
  packages/@essence/essence-constructor-classes/scripts/httpRequest.js
  packages/@essence/essence-constructor-classes/src/AppBar/config.json
  packages/@essence/essence-constructor-classes/src/AppBar/container/AppBar.tsx
  packages/@essence/essence-constructor-classes/src/AppBar/types.ts
  packages/@essence/essence-constructor-classes/src/Application/config.json
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/types.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/config.json
  packages/@essence/essence-constructor-classes/src/AuthForm/containers/AuthFormContainer.tsx
  packages/@essence/essence-constructor-classes/src/AuthForm/types.ts
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/containers/FieldItemSelector.tsx
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/store/FieldItemSelectorModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiAddrModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiMoModel.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/components/RepeaterGroup/RepeaterGroup.tsx
  packages/@essence/essence-constructor-classes/src/FieldSet/containers/FieldSetContainer.tsx
  packages/@essence/essence-constructor-classes/src/Filter/components/FilterButtons/FilterButtons.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridButtons/GridButtons.tsx
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/gridSetGlobalValues.ts
  packages/@essence/essence-constructor-classes/src/LangCombo/container/LangCombo.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelWrapper/PanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/RoadMap/store/RoadMapBtns.ts
  packages/@essence/essence-constructor-share/scripts/update.js
  packages/@essence/essence-constructor-share/src/constants/ui.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/types/Class.ts
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-share/src/utils/window/getExcelWindow.ts
Labels: enhancement

#395 CORE-1790 migrated application to new queries with public access
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
Labels: enhancement

#397 CORE-1798 fixed useInfo and redirect after sign in
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
Labels: bug, enhancement

#398 CORE-1800 documentation class
  package.json
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/scripts/fetchTypes.js
  packages/@essence/essence-constructor-classes/scripts/generateAutoDoc.js
  packages/@essence/essence-constructor-classes/scripts/utils/fetchClassAttrs.js
  packages/@essence/essence-constructor-classes/scripts/utils/fetchSession.js
  packages/@essence/essence-constructor-classes/scripts/utils/getdirs.js
  packages/@essence/essence-constructor-classes/scripts/utils/httpRequest.js
  packages/@essence/essence-constructor-classes/scripts/utils/updateClassAutoDoc.js
  packages/@essence/essence-constructor-classes/src/Application/README.md
  packages/@essence/essence-constructor-classes/src/Application/config.json
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Documentation/constants.ts
  packages/@essence/essence-constructor-classes/src/Documentation/containers/DocumentationContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/Documentation/containers/DocumentationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Documentation/index.ts
  packages/@essence/essence-constructor-classes/src/Documentation/store/DocumentationModel.ts
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
  packages/@essence/essence-constructor-classes/src/Pages/containers/PagesContainer.tsx
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/uicomponents/SideResizer/SideResizer.styles.ts
  packages/@essence/essence-constructor-website/src/register.ts
  yarn.lock
Labels: enhancement

#400 CORE-1790 recall applications after login
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
  packages/@essence/essence-constructor-share/src/types/Application.ts
  packages/@essence/essence-constructor-share/src/utils/test.tsx
Labels: enhancement

#401 CORE-1802 text component for render markdown documentation
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
  packages/@essence/essence-constructor-classes/src/Text/config.json
  packages/@essence/essence-constructor-classes/src/Text/containers/TextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Text/index.ts
  packages/@essence/essence-constructor-classes/src/Text/types.ts
  packages/@essence/essence-constructor-share/src/constants/variables.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: documentation, enhancement

#402 CORE-1802 documentation pages
  packages/@essence/essence-constructor-classes/src/AppBar/README.md
  packages/@essence/essence-constructor-classes/src/AppBar/config.json
  packages/@essence/essence-constructor-classes/src/AppBar/container/AppBar.styles.ts
  packages/@essence/essence-constructor-classes/src/AppBar/container/AppBar.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Box/containers/BoxContainer.tsx
  packages/@essence/essence-constructor-classes/src/Documentation/constants.ts
  packages/@essence/essence-constructor-classes/src/Documentation/containers/DocumentationContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/Documentation/containers/DocumentationContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldComputed/containers/FieldComputedContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.tsx
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/PagerView/containers/PagerViewContainer.tsx
  packages/@essence/essence-constructor-classes/src/PagerView/index.ts
  packages/@essence/essence-constructor-classes/src/Pages/containers/PagesContainer.tsx
  packages/@essence/essence-constructor-classes/src/PagesTree/config.json
  packages/@essence/essence-constructor-classes/src/PagesTree/container/PagesTree.styles.ts
  packages/@essence/essence-constructor-classes/src/PagesTree/container/PagesTree.tsx
  packages/@essence/essence-constructor-classes/src/PagesTree/stores/PagesTreeModel.ts
  packages/@essence/essence-constructor-classes/src/PagesTree/types.ts
  packages/@essence/essence-constructor-classes/src/Text/containers/TextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Text/types.ts
  packages/@essence/essence-constructor-share/src/uicomponents/MarkDown/index.ts
  packages/@essence/essence-constructor-share/src/uicomponents/MarkDown/renderers.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/index.ts
  packages/@essence/essence-constructor-share/src/utils/download.ts
  packages/@essence/essence-constructor-share/src/utils/parser.ts
  packages/@essence/essence-constructor-share/src/utils/redirect.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: documentation, enhancement

#403 CORE-1797 fixed validation statuses for numeric field
  packages/@essence/essence-constructor-classes/src/FieldNumeric/containers/FieldNumericContainer.tsx
Labels: bug

#404 CORE-1805 querymode for field combobox
  packages/@essence/essence-constructor-classes/src/FieldCombo/store/FieldComboModel.ts
  packages/@essence/essence-constructor-classes/src/LangCombo/container/LangCombo.tsx
  packages/@essence/essence-constructor-classes/src/ThemeCombo/container/ThemeCombo.tsx
Labels: bug, enhancement

#405 CORE-1801 error boundary for page
  packages/@essence/essence-constructor-classes/src/Pager/components/PagerErrorBoundary/PagerErrorBoundary.tsx
  packages/@essence/essence-constructor-classes/src/Pager/components/PagerErrorBoundary/index.ts
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
Labels: enhancement

#406 Fixed #399 revert focused color for checkbox
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.styles.ts
Labels: bug

#407 Fixes #391 revert logic for field table autoload
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
Labels: bug

#408 CORE-1796 improved exampled in promo
  packages/@essence/essence-constructor-classes/src/Promo/containers/PromoBehaviorText/PromoBehaviorText.tsx
  packages/@essence/essence-constructor-classes/src/Promo/mock/childsBehavior.ts
  packages/@essence/essence-constructor-classes/src/Promo/mock/childsBuild.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
Labels: bug

#410 CORE-1813 migrated clearvalue prop into initialization of the field
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldSet/containers/FieldSetContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/Form/validations/maxvalue.ts
  packages/@essence/essence-constructor-share/src/Form/validations/minvalue.ts
Labels: enhancement

#412 Fixed #411 - imptoved elevation for dark theme, redesign panel container
  packages/@essence/essence-constructor-classes/src/HistoryPanel/container/HistoryPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/Panel/Panel.styles.ts
  packages/@essence/essence-constructor-classes/src/Panel/components/Panel/Panel.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
  packages/@essence/essence-constructor-share/src/components.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.utils.tsx
Labels: bug

#416 Resolved #409 - changed color for disabled button in the collector
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/themeDark/getThemeDarkOverrides.ts
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/themeLight/getThemeLightOverrides.ts
Labels: bug

#417 Resolved #413 removed empty line for dark filter
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.tsx
Labels: bug

#418 #414 restore value for field table with multiselect
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-frame.json
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-preference.json
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-redirect.json
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-reports.json
  packages/@essence/essence-constructor-classes/src/FavoritePages/components/FavoritePage.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.types.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/utils/getRestoreValue.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/utils/getRestoredRecords.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/utils/index.ts
  packages/@essence/essence-constructor-classes/src/Grid/containers/GridContainer.tsx
  packages/@essence/essence-constructor-classes/src/PagesTree/components/TreeRow/TreeRow.tsx
Labels: enhancement

#415 Core 1792
  docs/ATTRIBUTES.md
  packages/@essence/essence-constructor-classes/scripts/fetchTypes.js
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-safe.json
  packages/@essence/essence-constructor-classes/src/Application/types.ts
  packages/@essence/essence-constructor-classes/src/BadgeBtn/container/BadgeBtn.tsx
  packages/@essence/essence-constructor-classes/src/ColumnText/containers/ColumnTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/ColumnText/utils/index.ts
  packages/@essence/essence-constructor-classes/src/ColumnText/utils/toString.ts
  packages/@essence/essence-constructor-classes/src/Documentation/containers/DocumentationContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/store/FieldComboModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldAddrConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldMoConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldRadio/stores/FieldRadioModel.ts
  packages/@essence/essence-constructor-classes/src/FieldRegexpRepl/containers/FieldRegexpReplContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldRegexpRepl/containers/FieldRegexpReplContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldRegexpRepl/index.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Filter/__mocks__/filterComboGlobalBc.ts
  packages/@essence/essence-constructor-classes/src/Filter/__mocks__/filterGlobalDefaultvaluesBc.ts
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/FormPanel/components/FormPanelGlobals/FormPanelGlobals.tsx
  packages/@essence/essence-constructor-classes/src/FormPanel/config.json
  packages/@essence/essence-constructor-classes/src/FormPanel/containers/FormPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/FormPanel/types.ts
  packages/@essence/essence-constructor-classes/src/Grid/components/GridTableHeader/GridTableHeader.tsx
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridCkId.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridValues.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/gridScrollToRecordAction.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/gridSetGlobalValues.ts
  packages/@essence/essence-constructor-classes/src/LangCombo/container/LangCombo.tsx
  packages/@essence/essence-constructor-classes/src/Promo/mock/childsBehavior.ts
  packages/@essence/essence-constructor-classes/src/Promo/mock/childsBuild.ts
  packages/@essence/essence-constructor-classes/src/RoadMap/store/RoadMapBtns.ts
  packages/@essence/essence-constructor-classes/src/ServiceHidden/containers/ServiceHiddenContainer.ts
  packages/@essence/essence-constructor-classes/src/ThemeCombo/container/ThemeCombo.tsx
  packages/@essence/essence-constructor-share/scripts/update.js
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/actions/saveAction.ts
  packages/@essence/essence-constructor-share/src/hooks/useFieldGetGlobal.ts
  packages/@essence/essence-constructor-share/src/hooks/useFieldSetGlobal.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/checkLoading.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/loadRecordsAction.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/utils/base.ts
  packages/@essence/essence-constructor-share/src/utils/findKey.ts
  packages/@essence/essence-constructor-share/src/utils/getMasterObject.ts
  packages/@essence/essence-constructor-share/src/utils/index.ts
  packages/@essence/essence-constructor-share/src/utils/redirect.ts
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: enhancement

#420 CORE-1818 fixed query for mo field
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiAddrModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiMoModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiModel/FieldMultiModel.ts
Labels: bug

#421 Core 1829
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Panel/components/Panel/Panel.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
Labels: bug

#422 CORE-1823 fixed valuefied for field radio
  packages/@essence/essence-constructor-classes/src/FieldRadio/stores/FieldRadioModel.ts
Labels: bug

#419 CORE-1828 removed fetching values from first grid in the window
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridValues.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/gridSetGlobalValues.ts
Labels: bug, enhancement

#423 Core 1823
  docs/ATTRIBUTES.md
  packages/@essence/essence-constructor-classes/src/FieldCssMeasure/containers/FieldCssMeasureContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/index.ts
Labels: bug, enhancement

#424 CORE-1829 removed elevation for not form panel
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
Labels: bug

#425 CORE-1834 removed auto select next field
  packages/@essence/essence-constructor-classes/src/FieldMulti/containers/FieldMultiContainer.tsx
Labels: bug

#426 init 2.5.0
  package.json
  packages/@essence/create-constructor-module/package.json
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-dll/package.json
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-eslint/package.json
  packages/@essence/essence-constructor-package-builder/package.json
  packages/@essence/essence-constructor-scripts/package.json
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-website/.env
  packages/@essence/essence-constructor-website/package.json
  yarn.lock
Labels: enhancement

#427 Core 1836
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelModelBtnConfigs.ts
  packages/@essence/essence-constructor-classes/src/Window/stores/WindowModel.ts
  packages/@essence/essence-constructor-share/src/actions/saveAction.ts
  packages/@essence/essence-constructor-share/src/models/ProgressModel/ProgressModel.ts
  packages/@essence/essence-constructor-share/src/models/SnackbarModel/SnackbarModel.ts
  packages/@essence/essence-constructor-share/src/types/ProgressModel.ts
Labels: bug

#428 CORE-1273 fix extra value
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
Labels: bug

#429 Core 1273
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
Labels: bug
