Repository essence-community/core-frontend, pull requests merged in 2020-04, with the labels that each got.

#279 CORE-1684 recalcuate height for tree grid
  packages/@essence/essence-constructor-components/src/stores/GridModel/GridModel.js
Labels: bug

#280 CORE-1619 added shadow for drawer
  packages/@essence/essence-constructor-classes/src/WindowDrawer/containers/WindowDrawerContainer.styles.ts
Labels: enhancement

#286 CORE-1689 common rules for tab panel
  packages/@essence/essence-constructor-classes/src/TabPanel/index.ts
Labels: bug

#285 CORE-1689 common rules for tab panel
  packages/@essence/essence-constructor-classes/src/TabPanel/index.ts
Labels: bug

#287 Core 1693 - improved UI for hidden/disabled tabs
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.dark.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.light.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverContent/TabPopoverContent.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.dark.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.light.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tabs/Tabs.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/hooks/useTab.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/store/TabPanelModel.ts
Labels: bug

#290 Core 1686
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.types.ts
  packages/@essence/essence-constructor-classes/src/Application/store/PagesModel.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/containers/AuthFormContainer.overrides.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/containers/AuthFormContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/containers/AuthFormContainer.tsx
  packages/@essence/essence-constructor-classes/src/AuthForm/images/dark_logo.png
  packages/@essence/essence-constructor-classes/src/AuthForm/images/light_logo.png
  packages/@essence/essence-constructor-classes/src/AuthForm/index.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/store/AuthFormModel.ts
  packages/@essence/essence-constructor-classes/src/AuthForm/utils/mergeOverridesDeep.ts
  packages/@essence/essence-constructor-classes/src/types.d.ts
  packages/@essence/essence-constructor-components/src/Button/BuilderMobxButton.jsx
  packages/@essence/essence-constructor-components/src/Theme/index.js
  packages/@essence/essence-constructor-components/src/stores/RecordsModel/RecordsModel.js
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/types/AuthModel.ts
  packages/@essence/essence-constructor-share/src/types/PageModel.ts
  packages/@essence/essence-constructor-website/.gitignore
  packages/@essence/essence-constructor-website/src/AppRoutes.jsx
  packages/@essence/essence-constructor-website/src/Components/MobxForm/MobxForm.js
  packages/@essence/essence-constructor-website/src/Components/MobxForm/index.js
  packages/@essence/essence-constructor-website/src/Pages/AuthPage/AuthPage.jsx
  packages/@essence/essence-constructor-website/src/Pages/AuthPage/AuthPageStyles/AuthPageStyles.js
  packages/@essence/essence-constructor-website/src/Pages/AuthPage/AuthPageStyles/AuthPageStylesDark.js
  packages/@essence/essence-constructor-website/src/Pages/AuthPage/AuthPageStyles/AuthPageStylesLight.js
  packages/@essence/essence-constructor-website/src/Pages/AuthPage/AuthPageStyles/index.js
  packages/@essence/essence-constructor-website/src/register.js
Labels: enhancement

#291 Core 1695
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/components/FieldMarkdownLabel/FieldMarkdownLabel.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/components/FieldMarkdownLabel/FieldMarkdownLabel.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/components/FieldMarkdownLabel/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.types.ts
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/index.ts
  packages/@essence/essence-constructor-classes/src/FieldTextarea/index.ts
  packages/@essence/essence-constructor-components/src/Form/BuilderForm.jsx
  packages/@essence/essence-constructor-website/src/register.js
  yarn.lock
Labels: enhancement

#292 CORE-1701 fixed overflow buttons for grid and panel
  packages/@essence/essence-constructor-components/src/Grid/BuilderBaseGrid.jsx
  packages/@essence/essence-constructor-components/src/Panel/BuilderFormPanel/BuilderFormPanel.jsx
Labels: bug

#293 Core 1699 fixed setgobal for service hidden
  packages/@essence/essence-constructor-classes/src/ServiceHidden/containers/ServiceHiddenContainer.ts
  packages/@essence/essence-constructor-share/src/hooks/useModel.tsx
  packages/@essence/essence-constructor-share/src/utils/transform.ts
Labels: bug

#294 CORE-1700 fixed free handler, migrated download into pages
  packages/@essence/essence-constructor-components/src/Button/handlers/freeHandler.ts
  packages/@essence/essence-constructor-share/src/actions/apiSaveAction.ts
  packages/@essence/essence-constructor-share/src/actions/download.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/request/requestCore.ts
  packages/@essence/essence-constructor-share/src/types/Base.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/types/RecordsModel.ts
Labels: enhancement

#296 CORE-1706 fixed moving tabs for page
  packages/@essence/essence-constructor-classes/src/Application/store/PagesModel.ts
  packages/@essence/essence-constructor-classes/src/OpenPageTabs/container/OpenPageTabs.tsx
  packages/@essence/essence-constructor-share/src/types/PagesModel.ts
Labels: bug

#297 CORE-1702 fixed getting preference
  packages/@essence/essence-constructor-share/src/models/ModulesModel/ModulesModel.ts
Labels: bug

#298 CORE-1702 unlink share
  packages/@essence/essence-constructor-dll/package.json
  packages/@essence/essence-constructor-dll/yarn.lock
Labels: bug

#299 CORE-1707 fixed max/min value with pointer
  packages/@essence/essence-constructor-components/src/Form/validations.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldCurrency/NumberFormatCustom.jsx
Labels: bug

#301 CORE-1059 fix expire session
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
Labels: bug

#300 Core 1174 add master rule and hiddenrule
  packages/@essence/essence-constructor-classes/src/ServiceHidden/containers/ServiceHiddenContainer.ts
  packages/@essence/essence-constructor-classes/src/ServiceHidden/index.ts
  packages/@essence/essence-constructor-classes/src/ServiceHidden/stores/ServiceHiddenModel.ts
  packages/@essence/essence-constructor-share/src/decorators/commonDecorator.tsx
Labels: enhancement

#302 CORE-1709 fixed issue with different user for restoring pages, improv…
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/mocks/page-safe.json
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/AuthModel.ts
  packages/@essence/essence-constructor-classes/src/Application/store/PagesModel.ts
  packages/@essence/essence-constructor-share/src/constants/variables.ts
Labels: enhancement

#304 CORE-1713 get btn without overrides, load required services only with…
  packages/@essence/essence-constructor-classes/src/Application/store/PagesModel.ts
  packages/@essence/essence-constructor-components/src/Panel/BuilderFormPanel/BuilderFormPanel.jsx
Labels: bug

#309 Core 1722 master
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/FilePanelModel.js
  packages/@essence/essence-constructor-share/src/decorators/utils.ts
  yarn.lock
Labels: bug

#308 CORE-1722 saveaction for file panel
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/FilePanelModel.js
Labels: bug

#311 CORE-1722 set default gate for download
  packages/@essence/essence-constructor-share/src/utils/download.ts
Labels: bug

#310 CORE-1722 set default gate for download
  packages/@essence/essence-constructor-share/src/utils/download.ts
Labels: bug

#312 CORE-1181 CheckBox to typescript
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/__tests__/FieldCheckbox.tsx
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.types.ts
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/index.ts
  packages/@essence/essence-constructor-classes/src/Pager/components/PagerWindowMessage.tsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldCheckbox/FieldCheckboxStyles/FieldCheckboxStyles.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldCheckbox/FieldCheckboxStyles/index.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldCheckbox/FieldCheckboxType.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldCheckbox/__tests__/FieldCheckbox.test.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldColorPicker/FieldColorPicker.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldRadioGroup/FieldRadioGroup.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldSmartMask/FieldSmartMask.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-components/src/TextField/TextField.jsx
  packages/@essence/essence-constructor-components/src/TextField/TextFieldComponents/TextFieldLabel/TextFieldLabel.jsx
  packages/@essence/essence-constructor-components/src/TextField/TextFieldComponents/TextFieldLabel/TextFieldLabelStyles.js
  packages/@essence/essence-constructor-share/src/uicomponents/SnackbarContentText/SnackbarContentText.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldLabel/TextFieldLabel.styles.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldLabel/TextFieldLabel.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldLabel/TextFieldLabel.types.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldLabel/index.ts
  packages/@essence/essence-constructor-share/src/uicomponents/index.ts
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: enhancement

#314 CORE-1179 EmptySpace to typescript
  packages/@essence/essence-constructor-classes/src/EmptySpace/__tests__/EmptySpace.test.jsx
  packages/@essence/essence-constructor-classes/src/EmptySpace/container/EmptySpace.tsx
  packages/@essence/essence-constructor-classes/src/EmptySpace/index.ts
  packages/@essence/essence-constructor-components/src/EmptySpace/EmptySpace.jsx
  packages/@essence/essence-constructor-components/src/EmptySpace/__tests__/EmptySpace.test.jsx
  packages/@essence/essence-constructor-share/src/decorators/commonDecorator.tsx
  packages/@essence/essence-constructor-website/src/register.ts
Labels: redesign

#315 laod-modules from topbtn
  packages/@essence/essence-constructor-share/src/utils/findClassNames.ts
Labels: bug
