Repository essence-community/core-frontend, pull requests merged in 2020-05, with the labels that each got.

#317 CORE-1731 getmastervalue for mo field
  packages/@essence/essence-constructor-components/src/stores/MoMultiField/MoMultiFieldConfigs.js
Labels: bug

#318 CORE-1732 fixed imask rules
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/imask.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/validationCharacters.json
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldSmartMask/FieldSmartMask.jsx
Labels: bug

#319 CORE-1738 use commonDecorator to check hidden/disabled tabs
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverContent/TabPopoverContent.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.styles.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tabs/Tabs.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/store/TabPanelModel.ts
Labels: bug

#320 CORE-1730 stabilization form and improved button for table field
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-components/src/TextField/BuilderField.jsx
  packages/@essence/essence-constructor-components/src/Window/BuilderWindow.jsx
  packages/@essence/essence-constructor-components/src/stores/TableFieldModel/TableFieldModel.js
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
Labels: bug

#321 Core 1187 Field Item Selector to TS
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/__tests__/FieldItemSelector.test.jsx
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/containers/FieldItemSelector.tsx
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/index.ts
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/store/FieldItemSelectorModel.ts
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/store/FieldItemSelectorModel.types.ts
  packages/@essence/essence-constructor-components/src/FieldItemSelector/__tests__/FieldItemSelector.test.jsx
  packages/@essence/essence-constructor-components/src/stores/FieldItemSelectorModel/FieldItemSelectorModel.js
  packages/@essence/essence-constructor-components/src/stores/FieldItemSelectorModel/FieldItemSelectorModelType.js
  packages/@essence/essence-constructor-components/src/stores/FieldItemSelectorModel/index.js
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: redesign

#322 CORE-1185 Field Set and Dynamic Panel to TS and fix Array Field
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldSet/__tests__/BuilderFieldSet.test.js
  packages/@essence/essence-constructor-classes/src/FieldSet/containers/FieldSetContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldSet/index.ts
  packages/@essence/essence-constructor-classes/src/PanelDynamic/__tests__/BuilderPanelDynamic.test.js
  packages/@essence/essence-constructor-classes/src/PanelDynamic/containers/PanelDynamicContainer.tsx
  packages/@essence/essence-constructor-classes/src/PanelDynamic/index.ts
  packages/@essence/essence-constructor-classes/src/PanelDynamic/store/PanelDynamicModel.ts
  packages/@essence/essence-constructor-components/src/FieldSet/BuilderFieldSet.js
  packages/@essence/essence-constructor-components/src/FieldSet/BuilderFieldSetType.js
  packages/@essence/essence-constructor-components/src/FieldSet/__tests__/BuilderFieldSet.test.js
  packages/@essence/essence-constructor-components/src/PanelDynamic/BuilderPanelDynamic.js
  packages/@essence/essence-constructor-components/src/PanelDynamic/__tests__/BuilderPanelDynamic.test.js
  packages/@essence/essence-constructor-components/src/stores/DynamicPanelModel/DynamicPanelModel.js
  packages/@essence/essence-constructor-components/src/stores/DynamicPanelModel/DynamicPanelModelType.js
  packages/@essence/essence-constructor-components/src/stores/DynamicPanelModel/index.js
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/index.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/constants/ui.ts
  packages/@essence/essence-constructor-share/src/context.ts
  packages/@essence/essence-constructor-share/src/decorators/commonDecorator.tsx
  packages/@essence/essence-constructor-share/src/utils/transform.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: redesign

#324 CORE-1742 fix reload page
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
Labels: bug

#325 CORE-1183 Field Period Date to TS
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldPeriod/__tests__/BuilderFieldPeriod.jsx
  packages/@essence/essence-constructor-classes/src/FieldPeriod/containers/FieldPeriod.tsx
  packages/@essence/essence-constructor-classes/src/FieldPeriod/index.ts
  packages/@essence/essence-constructor-components/src/FieldPeriod/BuilderFieldPeriod.jsx
  packages/@essence/essence-constructor-components/src/FieldPeriod/BuilderFieldPeriodSplit.jsx
  packages/@essence/essence-constructor-website/src/register.ts
Labels: redesign

#326 Core 1184 Text Field to TS
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/index.ts
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: redesign

#327 CORE-1208 fix form editing
  packages/@essence/essence-constructor-components/src/HistoryPanel/BuilderHistoryPanel.jsx
  packages/@essence/essence-constructor-components/src/Panel/BuilderFormPanel/BuilderFormPanel.jsx
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/useTextFieldProps.tsx
Labels: bug

#328 CORE-1209 fix Field Repeater min size
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
Labels: bug

#330 CORE-1725 align, contentview, width for filter & filter extended
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FilterExtended/container/FilterExtended.tsx
Labels: enhancement

#331 Core 1747
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridColumns.ts
  packages/@essence/essence-constructor-classes/src/GridHFDate/containers/GridHFDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/GridHFDefault/containers/GridHFDefaultContainer.tsx
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/components/GridHFContent/GridHFContent.tsx
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/components/GridHFIcon/GridHFIcon.styles.ts
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/components/GridHFIcon/GridHFIcon.tsx
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/components/GridHeaderFilter/GridHeaderFilter.tsx
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/containers/GridHeaderDefaultContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/containers/GridHeaderDefaultContainer.tsx
  packages/@essence/essence-constructor-classes/src/NotificationPanel/components/NotificationsTabs/NotificationTab.tsx
  packages/@essence/essence-constructor-classes/src/NotificationPanel/components/NotificationsTabs/NotificationsTab.types.ts
  packages/@essence/essence-constructor-classes/src/NotificationPanel/components/NotificationsTabs/NotificationsTabs.ts
  packages/@essence/essence-constructor-classes/src/NotificationPanel/container/NotificationPanel.tsx
  packages/@essence/essence-constructor-share/src/models/GlobalRecordsModel/GlobalRecordsModel.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelAbstract.ts
  packages/@essence/essence-constructor-share/src/models/SnackbarModel/SnackbarModel.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/utils/test.tsx
  packages/@essence/essence-constructor-share/src/utils/window/getDefaultWindowBc.ts
Labels: bug, enhancement, redesign

#333 CORE-1752 migrated mask into ts, fixed grid with record and grid colu…
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridColgroup/GridColgroup.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/VirtualizedGrid/VirtualizedGrid.tsx
  packages/@essence/essence-constructor-components/package.json
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateRC.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/FieldMask.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/formatChars.json
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/validCharToVal.json
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMask/validationCharacters.json
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldSmartMask/FieldSmartMask.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/index.ts
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/useTextFieldProps.tsx
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/useTextFieldProps.types.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/TextFieldMask.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/__tests__/FieldMask.test.jsx
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/__tests__/imask.test.js
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/imask.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/index.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/maskConfig.ts
  packages/@essence/essence-constructor-share/src/uicomponents/index.ts
  packages/@essence/essence-constructor-share/yarn.lock
  yarn.lock
Labels: bug, enhancement, redesign

#334 CORE-1752 migrated smart mask into ts
  packages/@essence/essence-constructor-classes/src/FieldText/FieldText.types.ts
  packages/@essence/essence-constructor-classes/src/FieldText/components/FieldTextSmartMask/FieldTextSmartMask.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/components/FieldTextSmartMask/__tests__/FieldTextSmartMask.test.jsx
  packages/@essence/essence-constructor-classes/src/FieldText/components/FieldTextSmartMask/index.ts
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/utils/handleGetNewValueAndSelection.ts
  packages/@essence/essence-constructor-classes/src/FieldText/utils/handleProcessBFormat.ts
  packages/@essence/essence-constructor-classes/src/FieldText/utils/handleProcessRFormat.ts
  packages/@essence/essence-constructor-classes/src/FieldText/utils/index.ts
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldSmartMask/FieldSmartMask.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/TextFieldMask.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/index.ts
Labels: redesign

#335 Core 1753
  packages/@essence/essence-constructor-classes/src/Application/components/ApplicationWindows.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.types.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/getGridValues.ts
  packages/@essence/essence-constructor-classes/src/Pager/components/PagerWindows.tsx
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/README.md
  packages/@essence/essence-constructor-classes/src/Window/__tests__/BuilderWindow.test.js
  packages/@essence/essence-constructor-classes/src/Window/components/WindowButtons/WindowButtons.tsx
  packages/@essence/essence-constructor-classes/src/Window/components/WindowButtons/index.ts
  packages/@essence/essence-constructor-classes/src/Window/components/WindowCancel/WindowCancel.styles.ts
  packages/@essence/essence-constructor-classes/src/Window/components/WindowCancel/WindowCancel.tsx
  packages/@essence/essence-constructor-classes/src/Window/components/WindowCancel/index.ts
  packages/@essence/essence-constructor-classes/src/Window/containers/WindowContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/Window/containers/WindowContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/index.ts
  packages/@essence/essence-constructor-classes/src/Window/stores/WindowModel.ts
  packages/@essence/essence-constructor-classes/src/Window/utils/checkEditable.ts
  packages/@essence/essence-constructor-classes/src/Window/utils/getModeTitle.ts
  packages/@essence/essence-constructor-classes/src/Window/utils/getWindowChilds.ts
  packages/@essence/essence-constructor-classes/src/Window/utils/index.ts
  packages/@essence/essence-constructor-classes/src/WindowDrawer/containers/WindowDrawerContainer.tsx
  packages/@essence/essence-constructor-components/src/Window/BuilderWindow.jsx
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowButtons/BuilderWindowButtonCustom.jsx
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowButtons/BuilderWindowButtonDefault.jsx
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowStyles/BuilderWindowStyles.js
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowStyles/BuilderWindowStylesDark.js
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowStyles/BuilderWindowStylesLight.js
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowStyles/index.js
  packages/@essence/essence-constructor-components/src/Window/BuilderWindowType.js
  packages/@essence/essence-constructor-components/src/Window/index.js
  packages/@essence/essence-constructor-components/src/WindowMessage/WindowMessage.jsx
  packages/@essence/essence-constructor-components/src/WindowMessage/WindowMessageButton.jsx
  packages/@essence/essence-constructor-components/src/WindowMessage/WindowMessageCancel.jsx
  packages/@essence/essence-constructor-components/src/WindowMessage/WindowMessageStyle/WindowMessageStyleDark.js
  packages/@essence/essence-constructor-components/src/WindowMessage/WindowMessageStyle/WindowMessageStyleLight.js
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/FilePanelModel.js
  packages/@essence/essence-constructor-components/src/stores/PageModel/PageModel.js
  packages/@essence/essence-constructor-components/src/stores/PageModel/PageModelType.js
  packages/@essence/essence-constructor-components/src/stores/WindowModel/WindowModel.js
  packages/@essence/essence-constructor-components/src/stores/WindowModel/WindowModelTypes.js
  packages/@essence/essence-constructor-components/src/stores/WindowModel/index.js
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelAbstract.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelRedirect.ts
  packages/@essence/essence-constructor-share/src/models/WindowModel/WindowModel.ts
  packages/@essence/essence-constructor-share/src/models/WindowModel/WindowModel.types.ts
  packages/@essence/essence-constructor-share/src/models/WindowModel/index.ts
  packages/@essence/essence-constructor-share/src/models/index.ts
  packages/@essence/essence-constructor-share/src/types/Builder.ts
  packages/@essence/essence-constructor-share/src/types/Class.ts
  packages/@essence/essence-constructor-share/src/types/PageModel.ts
  packages/@essence/essence-constructor-share/src/types/WindowModel.ts
  packages/@essence/essence-constructor-share/src/types/index.ts
  packages/@essence/essence-constructor-share/src/uicomponents/Focusable/Focusable.tsx
  packages/@essence/essence-constructor-share/src/utils/window/createWindowProps.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: enhancement, redesign

#336 CORE-1747 check correct key for filter column
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/components/GridHFIcon/GridHFIcon.tsx
Labels: bug

#337 CORE-1744 fixed grid redirect and filter
  packages/@essence/essence-constructor-classes/src/Filter/components/FilterButtons/FilterButtons.tsx
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
Labels: bug

#338 CORE-1753 improved width for focusable window, fixed nested window
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/containers/WindowContainer.styles.ts
Labels: bug

#339 CORE-1753 show windows only for pagetStore pager
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
Labels: bug

#340 CORE-1758 fixed choosing value in field table
  packages/@essence/essence-constructor-classes/src/Button/hooks/useButtonClick.ts
  packages/@essence/essence-constructor-classes/src/ColumnTree/components/ColumnTreeSchevron/ColumnTreeSchevron.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/components/GridTable/GridTable.tsx
  packages/@essence/essence-constructor-share/src/types/StoreBaseModel.ts
Labels: bug

#341 Core 1758
  packages/@essence/essence-constructor-classes/src/Application/store/PagesModel.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/setGridSelections.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/setGridSelectionsTop.ts
  packages/@essence/essence-constructor-share/src/hooks/useFieldGetGlobal.ts
  packages/@essence/essence-constructor-share/src/hooks/useFieldSetGlobal.ts
Labels: bug

#343 Core 1734
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-share/src/Form/validations/afterNotRequired.ts
  packages/@essence/essence-constructor-share/src/Form/validations/beforeNotRequired.ts
  packages/@essence/essence-constructor-share/src/Form/validations/dates.ts
  packages/@essence/essence-constructor-share/src/Form/validations/index.ts
  packages/@essence/essence-constructor-share/src/Form/validations/maxsize.ts
  packages/@essence/essence-constructor-share/src/Form/validations/maxvalue.ts
  packages/@essence/essence-constructor-share/src/Form/validations/maxvaluedate.ts
  packages/@essence/essence-constructor-share/src/Form/validations/minsize.ts
  packages/@essence/essence-constructor-share/src/Form/validations/minvalue.ts
  packages/@essence/essence-constructor-share/src/Form/validations/minvaluedate.ts
  packages/@essence/essence-constructor-share/src/Form/validations/regex.ts
  packages/@essence/essence-constructor-share/src/Form/validations/reqcount.ts
  packages/@essence/essence-constructor-share/src/Form/validations_old.js
  packages/@essence/essence-constructor-share/src/constants/base.ts
  packages/@essence/essence-constructor-share/yarn.lock
  yarn.lock
Labels: enhancement, redesign

#344 CORE-1758 liste for history to open ruter on back history
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/hooks/index.ts
  packages/@essence/essence-constructor-classes/src/Application/hooks/useHistoryListen.ts
Labels: bug, enhancement

#345 CORE-1210 fixed
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FormPanel/containers/FormPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelWrapper/HistoryPanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/HistoryPanel/container/HistoryPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/Pager/containers/PagerContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.styles.ts
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelWrapper/PanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelWrapper/PanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
Labels: bug

#347 CORE-1710 do not pass children through all grid components
  packages/@essence/essence-constructor-classes/src/Grid/components/BaseGrid/BaseGrid.tsx
  packages/@essence/essence-constructor-share/src/utils/storage.ts
Labels: bug

#348 Core 1746
  packages/@essence/essence-constructor-classes/src/ColumnCheckbox/containers/ColumnCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/setGridSelections.ts
  packages/@essence/essence-constructor-classes/src/Grid/utils/setGridSelectionsTop.ts
  packages/@essence/essence-constructor-share/scripts/update.js
  packages/@essence/essence-constructor-share/src/types/Builder.ts
Labels: enhancement

#349 CORE-1761 mirated field multi into ts, improved field combo
  packages/@essence/essence-constructor-classes/src/FieldCombo/components/FieldComboInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/components/FieldComboList.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/container/FieldCombo.types.ts
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/__tests__/FieldMulti.test.jsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiContent/FieldMultiContent.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiContent/FieldMultiContent.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiContent/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiInput/FieldMultiInput.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiInput/FieldMultiInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiInput/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/containers/FieldMultiContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/containers/FieldMultiContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiAddrModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiMoModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiModel/FieldMultiModel.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiModel/FieldMultiModel.types.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/stores/FieldMultiModel/index.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldAddrConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldMoConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/index.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/FieldText/components/FieldTextSmartMask/FieldTextSmartMask.tsx
  packages/@essence/essence-constructor-classes/src/Filter/components/FilterButtons/FilterButtons.tsx
  packages/@essence/essence-constructor-components/src/TextField/BuilderField.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMulti/FieldMulti.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMulti/FieldMultiLoader.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMulti/FieldMultiStyles/index.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldMulti/FieldMultiTypes.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-components/src/stores/AddrMultiField/AddrMultiField.js
  packages/@essence/essence-constructor-components/src/stores/AddrMultiField/AddrMultiFieldType.js
  packages/@essence/essence-constructor-components/src/stores/AddrMultiField/index.js
  packages/@essence/essence-constructor-components/src/stores/MoMultiField/MoMultiField.js
  packages/@essence/essence-constructor-components/src/stores/MoMultiField/MoMultiFieldType.js
  packages/@essence/essence-constructor-components/src/stores/MoMultiField/index.js
  packages/@essence/essence-constructor-components/src/stores/index.js
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/useTextFieldProps.tsx
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelRedirect.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: enhancement, redesign

#351 CORE-1761 migrated field color into ts
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorContent/FieldColorContent.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorContent/index.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorPicker/FieldColorPicker.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorPicker/FieldColorPicker.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorPicker/index.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorPickerInput/FieldColorPickerInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/components/FieldColorPickerInput/index.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/constants.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/containers/FieldColorContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FieldColor/containers/FieldColorContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/index.ts
  packages/@essence/essence-constructor-components/package.json
  packages/@essence/essence-constructor-components/src/ColorPicker/ColorPicker.jsx
  packages/@essence/essence-constructor-components/src/ColorPicker/ColorPickerStyles.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldColorPicker/FieldColorPicker.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldColorPicker/FieldColorPickerStyles/FieldColorPickerStyles.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldColorPicker/FieldColorPickerStyles/index.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldColorPicker/FieldColorPickerType.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-website/src/register.ts
  yarn.lock
Labels: redesign

#350 CORE-1182 Field Date to TS
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/FieldDate/__tests__/FieldDateRC.test.jsx
  packages/@essence/essence-constructor-classes/src/FieldDate/components/FieldDate.types.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/components/FieldDateBase/FieldDateBase.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/components/FieldDateMain/FieldDateMain.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/components/FieldDateMonth/FieldDateMonth.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/components/PickerOverride/PickerOverride.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.types.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/hook/useFieldDisabled.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/index.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/util/Util.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/util/locale.ts
  packages/@essence/essence-constructor-classes/src/types.d.ts
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateBase.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateMain.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateMonth.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateRC.jsx
  packages/@essence/essence-constructor-components/src/TextField/Fields/FieldDateRC/FieldDateRCSStyles/index.js
  packages/@essence/essence-constructor-components/src/TextField/Fields/index.js
  packages/@essence/essence-constructor-website/src/register.ts
  yarn.lock
Labels: enhancement, redesign

#353 CORE-1764 apply globals before await forms for redirect
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelRedirect.ts
Labels: bug, enhancement

#355 CORE-1180 File Panel to TS
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/FilePanel/__tests__/BuilderFilePanel.test.js
  packages/@essence/essence-constructor-classes/src/FilePanel/components/FileRecord/FileRecord.styles.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/components/FileRecord/FileRecord.tsx
  packages/@essence/essence-constructor-classes/src/FilePanel/components/PanelWrapper/PanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/components/PanelWrapper/PanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelModelBtnConfigs.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/index.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/store/FilePanelModel.ts
  packages/@essence/essence-constructor-components/src/FilePanel/BuilderFilePanel.jsx
  packages/@essence/essence-constructor-components/src/FilePanel/FileRecord/FileRecord.jsx
  packages/@essence/essence-constructor-components/src/FilePanel/FileRecord/FileRecordStyles/FileRecordStyles.js
  packages/@essence/essence-constructor-components/src/FilePanel/FileRecord/FileRecordStyles/index.js
  packages/@essence/essence-constructor-components/src/FilePanel/Styles/BuilderFilePanelStylesDark.js
  packages/@essence/essence-constructor-components/src/FilePanel/Styles/BuilderFilePanelStylesLight.js
  packages/@essence/essence-constructor-components/src/FilePanel/Styles/index.js
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/FilePanelModel.js
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/FilePanelModelTypes.js
  packages/@essence/essence-constructor-components/src/stores/FilePanelModel/index.js
  packages/@essence/essence-constructor-website/src/register.ts
  yarn.lock
Labels: enhancement, redesign

#356 Core 1758
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/themeDark/getThemeDark.ts
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/themeLight/getThemeLight.ts
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/utils/getFirstValues.ts
  packages/@essence/essence-constructor-classes/src/FieldCombo/utils/index.ts
  packages/@essence/essence-constructor-classes/src/FieldRadio/containers/FieldRadioContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.tsx
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/containers/GridContainer.tsx
  packages/@essence/essence-constructor-classes/src/LangCombo/container/LangCombo.tsx
  packages/@essence/essence-constructor-share/src/hooks/useModel.tsx
  packages/@essence/essence-constructor-website/src/App.tsx
Labels: bug, enhancement

#357 CORE-1218 Tootip to TS
  packages/@essence/essence-constructor-components/src/Tooltip/Tooltip.jsx
  packages/@essence/essence-constructor-components/src/Tooltip/TooltipStyles/index.js
  packages/@essence/essence-constructor-components/src/index.js
  packages/@essence/essence-constructor-share/src/uicomponents/Tooltip/Tooltip.styles.ts
  packages/@essence/essence-constructor-share/src/uicomponents/Tooltip/Tooltip.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/Tooltip/index.ts
  packages/@essence/essence-constructor-share/src/uicomponents/index.ts
  packages/@essence/essence-constructor-website/src/App.tsx
Labels: enhancement, redesign

#358 CORE-1218 fix
  packages/@essence/essence-constructor-share/src/uicomponents/Tooltip/Tooltip.tsx
Labels: bug

#360 CORE-1223 fix date
  packages/@essence/essence-constructor-classes/src/FieldDate/components/FieldDate.types.ts
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/util/Util.ts
Labels: bug

#361 CORE-1710 fixed merge issue
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
Labels: bug

#362 CORE-1770 changed field master value and reload master services
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
Labels: bug, enhancement

#363 Core 1770
  packages/@essence/essence-constructor-classes/src/ColumnTree/containers/ColumnTreeContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/containers/FieldColorContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/components/FieldComboInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/hook/useFieldDateDisabled.ts
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/containers/FieldItemSelector.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/components/FieldMultiInput/FieldMultiInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/containers/FieldMultiContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldNumeric/containers/FieldNumericContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldPassword/containers/FIeldPasswordContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldRadio/containers/FieldRadioContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/components/FieldTableInput/FieldTableInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridInlineTable/GridInlineTable.tsx
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/components.ts
  packages/@essence/essence-constructor-share/src/hooks/index.ts
  packages/@essence/essence-constructor-share/src/hooks/useFieldDisabled.ts
  packages/@essence/essence-constructor-share/src/hooks/useModel.tsx
Labels: bug, enhancement

#365 CORE-1770 fixed upload file and reimplemented upload progress
  packages/@essence/essence-constructor-classes/src/Button/containers/ButtonContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/components/WindowButtons/WindowButtons.tsx
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-share/src/actions/apiSaveAction.ts
  packages/@essence/essence-constructor-share/src/actions/saveAction.ts
  packages/@essence/essence-constructor-share/src/constants/base.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/request/baseRequest/baseAxiosRequest.ts
  packages/@essence/essence-constructor-share/src/request/baseRequest/baseRequest.ts
  packages/@essence/essence-constructor-share/src/request/baseRequest/baseRequest.types.ts
  packages/@essence/essence-constructor-share/src/request/baseRequest/index.ts
  packages/@essence/essence-constructor-share/src/request/index.ts
  packages/@essence/essence-constructor-share/src/request/request.ts
  packages/@essence/essence-constructor-share/src/request/requestCore.ts
  packages/@essence/essence-constructor-share/src/types/Module.ts
  packages/@essence/essence-constructor-share/src/types/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/types/Request.ts
  packages/@essence/essence-constructor-share/src/types/index.ts
  packages/@essence/essence-constructor-share/src/utils/redirect.ts
  packages/@essence/essence-constructor-share/yarn.lock
  yarn.lock
Labels: bug, enhancement

#366 CORE-1770 improved print to excel
  packages/@essence/essence-constructor-classes/src/Grid/utils/printExcel.ts
  packages/@essence/essence-constructor-share/src/Form/Field.ts
Labels: bug

#367 CORE-1770 aign for pagination of the table
  packages/@essence/essence-constructor-classes/src/Grid/components/GridButtons/GridButtons.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridTable/GridTable.styles.ts
  packages/@essence/essence-constructor-classes/src/Grid/components/GridTable/GridTable.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/Pagination/Pagination.tsx
Labels: bug

#368 CORE-1770 fixed save action (incorrect default query and axios data)
  packages/@essence/essence-constructor-share/src/actions/saveAction.ts
  packages/@essence/essence-constructor-share/src/request/request.ts
  packages/@essence/essence-constructor-share/src/types/Request.ts
Labels: bug

#364 CORE-1217 defaultValuQuery to TS
  packages/@essence/essence-constructor-classes/src/FieldCheckbox/containers/FieldCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldColor/containers/FieldColorContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldHidden/containers/FieldHiddenContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/containers/FieldMarkdownContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMulti/containers/FieldMultiContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldNumeric/containers/FieldNumericContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldPassword/containers/FIeldPasswordContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldRadio/containers/FieldRadioContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTextarea/containers/FieldTextareaContainer.tsx
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/hooks/index.ts
  packages/@essence/essence-constructor-share/src/hooks/useDefaultValueQuery.ts
Labels: enhancement, redesign

#369 Core 1770
  package.json
  packages/@essence/create-constructor-module/package.json
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/FieldRadio/containers/FieldRadioContainer.tsx
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.tsx
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-eslint/package.json
  packages/@essence/essence-constructor-package-builder/package.json
  packages/@essence/essence-constructor-scripts/package.json
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-website/.env
  packages/@essence/essence-constructor-website/package.json
  yarn.lock
Labels: enhancement

#370 CORE-1770 fallback to none bc
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
Labels: bug

#373 CORE-1772 fix 7,8,10
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
Labels: bug

#372 CORE-1772 fix 7,8,10
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
Labels: bug

#371 Core 1772
  packages/@essence/essence-constructor-classes/src/FieldCombo/components/FieldComboInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldHidden/containers/FieldHiddenContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldText/containers/FieldTextContainer.tsx
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/FormPanel/containers/FormPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/BaseGrid/BaseGrid.tsx
  packages/@essence/essence-constructor-classes/src/GridHFDate/containers/GridHFDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelButtons/HistoryPanelButtons.tsx
  packages/@essence/essence-constructor-classes/src/HistoryPanel/container/HistoryPanelContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/HistoryPanel/container/HistoryPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.styles.ts
  packages/@essence/essence-constructor-share/src/Form/Field.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelRedirect.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/types/Base.ts
  packages/@essence/essence-constructor-share/src/types/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/uicomponents/UIForm/UIForm.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/UIForm/UIForm.types.ts
Labels: bug

#374 CORE-1772 migrated theme combo into theme settings
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/Theme.tsx
  packages/@essence/essence-constructor-classes/src/Application/containers/ApplicationContainer.tsx
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/ColumnDetail/containers/ColumnDetailContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/components/BaseGrid/BaseGrid.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridDetail/GridDetail.tsx
  packages/@essence/essence-constructor-classes/src/ThemeCombo/container/ThemeCombo.tsx
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/constants/deprecated.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModelAbstract.ts
  packages/@essence/essence-constructor-website/src/index.tsx
  packages/@essence/essence-constructor-website/src/themeCheck.js
Labels: bug

#375 CORE-1772 fix dark
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
Labels: bug

#377 CORE-1772 fix File Panel
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/containers/FilePanelContainer.tsx
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
Labels: bug

#376 Core 1772
  packages/@essence/essence-constructor-classes/src/Application/components/Theme/themeLight/getThemeLight.ts
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/Box/containers/BoxContainer.tsx
  packages/@essence/essence-constructor-classes/src/ColumnCheckbox/containers/ColumnCheckboxContainer.tsx
  packages/@essence/essence-constructor-classes/src/ColumnTree/components/ColumnTreeSchevron/ColumnTreeSchevron.tsx
  packages/@essence/essence-constructor-classes/src/FieldDate/containers/FieldDateContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldItemSelector/containers/FieldItemSelector.tsx
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/components/GridButtons/GridButtons.tsx
  packages/@essence/essence-constructor-classes/src/Grid/components/GridTableHeader/GridTableHeader.tsx
  packages/@essence/essence-constructor-classes/src/Grid/containers/GridSettingsContainer.tsx
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.ts
  packages/@essence/essence-constructor-classes/src/Grid/stores/GridModel/GridModel.types.ts
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/containers/GridHeaderDefaultContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/GridHeaderDefault/containers/GridHeaderDefaultContainer.tsx
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.styles.ts
  packages/@essence/essence-constructor-classes/src/RoadMap/companents/RoadMapTab/RoadMapTab.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/containers/TabPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/containers/WindowContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/stores/WindowModel.ts
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/Form/types.ts
  packages/@essence/essence-constructor-share/src/Form/validations/regex.ts
  packages/@essence/essence-constructor-share/src/decorators/commonDecorator.tsx
  packages/@essence/essence-constructor-share/src/hooks/useTextFieldProps/useTextFieldProps.tsx
  packages/@essence/essence-constructor-share/src/models/PageModel/PageModel.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/models/StoreBaseModel/StoreBaseModel.ts
  packages/@essence/essence-constructor-share/src/types/StoreBaseModel.ts
  packages/@essence/essence-constructor-share/src/uicomponents/UIForm/UIForm.tsx
  packages/@essence/essence-constructor-share/src/utils/test.tsx
  packages/@essence/essence-constructor-share/src/utils/window/getWindowChilds.ts
Labels: bug

#378 CORE-1772 reset data when click reset button for the filter
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
Labels: bug

#379 CORE-1231 Fix master File Panel
  packages/@essence/essence-constructor-classes/src/FilePanel/store/FilePanelModel.ts
Labels: bug

#380 Core 1775
  packages/@essence/essence-constructor-classes/src/Button/components/IconButton/IconButton.tsx
  packages/@essence/essence-constructor-classes/src/Button/utils/getColor.ts
  packages/@essence/essence-constructor-classes/src/FieldText/components/FieldTextSmartMask/FieldTextSmartMask.tsx
  packages/@essence/essence-constructor-classes/src/Filter/components/FilterButtons/FilterButtons.tsx
  packages/@essence/essence-constructor-classes/src/FormPanel/components/FormPanelGlobals/FormPanelGlobals.tsx
  packages/@essence/essence-constructor-classes/src/FormPanel/components/FormPanelGlobals/index.ts
  packages/@essence/essence-constructor-classes/src/FormPanel/containers/FormPanelContainer.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/Tab/Tab.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.tsx
  packages/@essence/essence-constructor-share/src/Form/Form.ts
  packages/@essence/essence-constructor-share/src/decorators/commonDecorator.tsx
  packages/@essence/essence-constructor-share/src/hooks/index.ts
  packages/@essence/essence-constructor-share/src/hooks/useCommon/index.ts
  packages/@essence/essence-constructor-share/src/hooks/useCommon/isDisabled.ts
  packages/@essence/essence-constructor-share/src/hooks/useCommon/useCommon.ts
  packages/@essence/essence-constructor-share/src/uicomponents/TextFieldMask/TextFieldMask.tsx
  packages/@essence/essence-constructor-share/src/uicomponents/UIForm/UIForm.tsx
Labels: bug, enhancement

#381 Core 1775
  packages/@essence/essence-constructor-classes/src/FieldMulti/utils/getFieldMoConfig.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
Labels: bug

#382 Core 1740
  packages/@essence/essence-constructor-classes/src/StaticPreference/containers/StaticPreferenceContainer.tsx
  packages/@essence/essence-constructor-classes/src/StaticRedirect/containers/StaticRedirectContainer.tsx
  packages/@essence/essence-constructor-classes/src/Window/stores/WindowModel.ts
  packages/@essence/essence-constructor-dll/package.json
  packages/@essence/essence-constructor-scripts/config/webpack.config.js
  packages/@essence/essence-constructor-scripts/template_example/src/App.tsx
  packages/@essence/essence-constructor-scripts/template_example/src/containers/ExampleContainer.tsx
  packages/@essence/essence-constructor-scripts/template_typescript/src/App.tsx
  packages/@essence/essence-constructor-scripts/yarn.lock
  packages/@essence/essence-constructor-share/src/constants/base.ts
  packages/@essence/essence-constructor-share/src/models/ModulesModel/ModulesModel.ts
  packages/@essence/essence-constructor-share/src/request/request.ts
  packages/@essence/essence-constructor-share/src/uicomponents/Tooltip/Tooltip.tsx
  packages/@essence/essence-constructor-share/src/utils/index.ts
  packages/@essence/essence-constructor-share/src/utils/preference.ts
  packages/@essence/essence-constructor-website/src/register.ts
Labels: bug, enhancement
