Repository essence-community/core-frontend, pull requests merged in 2021-03, with the labels that each got.

#562 fix panel title
  packages/@essence/essence-constructor-classes/src/FieldRepeater/components/RepeaterGroup/RepeaterGroup.tsx
  packages/@essence/essence-constructor-classes/src/FieldRepeater/components/RepeaterGroup/RepeaterGroup.types.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
  packages/@essence/essence-constructor-classes/src/Panel/containers/PanelContainer.tsx
Labels: bug

#563 fix and add width
  packages/@essence/essence-constructor-classes/src/FieldRepeater/components/Group/Group.tsx
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.tsx
Labels: bug, enhancement

#570 fix module and update mobx
  packages/@essence/essence-constructor-classes/package.json
  packages/@essence/essence-constructor-classes/src/Application/store/ApplicationModel.ts
  packages/@essence/essence-constructor-classes/src/PanelDynamic/containers/PanelDynamicContainer.tsx
  packages/@essence/essence-constructor-dll/.gitignore
  packages/@essence/essence-constructor-dll/config/webpack.config.js
  packages/@essence/essence-constructor-dll/package.json
  packages/@essence/essence-constructor-dll/yarn.lock
  packages/@essence/essence-constructor-scripts/config/webpack.config.js
  packages/@essence/essence-constructor-scripts/scripts/zip.js
  packages/@essence/essence-constructor-scripts/yarn.lock
  packages/@essence/essence-constructor-share/package.json
  packages/@essence/essence-constructor-share/src/models/ModulesModel/ModulesModel.ts
  packages/@essence/essence-constructor-share/src/models/ProgressModel/ProgressModel.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/checkLoading.ts
  packages/@essence/essence-constructor-share/src/models/SettingsModel/SettingsModel.ts
  packages/@essence/essence-constructor-share/src/models/SnackbarModel/SnackbarModel.ts
  packages/@essence/essence-constructor-share/src/models/ViewModel/ViewModel.ts
  packages/@essence/essence-constructor-share/src/utils/browser.ts
  packages/@essence/essence-constructor-share/yarn.lock
  packages/@essence/essence-constructor-website/package.json
  yarn.lock
Labels: bug, enhancement

#572 fix nested field
  packages/@essence/essence-constructor-classes/src/FieldFile/containers/FieldFileContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldFile/store/FileInputModel.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/Store/FieldRepeaterModel.ts
  packages/@essence/essence-constructor-classes/src/FieldRepeater/containers/FieldRepeaterContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/containers/FieldTableContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
Labels: bug

#573 fix label
  packages/@essence/essence-constructor-classes/src/FieldGroup/containers/FieldGroupContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldMarkdown/components/FieldMarkdownLabel/FieldMarkdownLabel.tsx
  packages/@essence/essence-constructor-classes/src/FieldRepeater/components/Group/Group.tsx
  packages/@essence/essence-constructor-classes/src/FilterExtended/container/FilterExtended.tsx
  packages/@essence/essence-constructor-classes/src/Iframe/components/IFrame.tsx
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.styles.ts
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.tsx
  packages/@essence/essence-constructor-classes/src/RoadMap/companents/RoadMapTabs/RoadMapTabs.tsx
  packages/@essence/essence-constructor-classes/src/RoadMap/store/RoadMapBtns.ts
  packages/@essence/essence-constructor-classes/src/RoadMap/store/RoadMapModel.ts
  packages/@essence/essence-constructor-classes/src/TabPanel/components/TabPopoverItem/TabPopoverItem.tsx
  packages/@essence/essence-constructor-classes/src/TabPanel/store/TabPanelModel.ts
Labels: bug

#574 fix font size
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.styles.ts
Labels: bug

#575 fix btn roadmap and collapsible
  packages/@essence/essence-constructor-classes/src/PanelCollapsible/containers/PanelCollapsible.styles.ts
  packages/@essence/essence-constructor-classes/src/RoadMap/store/RoadMapBtns.ts
Labels: bug

#577 fix warning
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
Labels: bug

#578 #571 restyle black panels
  packages/@essence/essence-constructor-classes/src/Filter/containers/FilterContainer.styles.ts
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelWrapper/HistoryPanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelWrapper/HistoryPanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.styles.ts
  packages/@essence/essence-constructor-share/src/uicomponents/EmptyTitle/EmptyTitle.styles.ts
Labels: bug

#579 447 remove white background on form
  packages/@essence/essence-constructor-classes/src/FilePanel/components/PanelWrapper/PanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/FilePanel/components/PanelWrapper/PanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelWrapper/HistoryPanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/HistoryPanel/component/HistoryPanelWrapper/HistoryPanelWrapper.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelWrapper/PanelWrapper.styles.ts
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelWrapper/PanelWrapper.tsx
Labels: bug

#582 Add disabled filter when editing.
  packages/@essence/essence-constructor-classes/src/Grid/components/BaseGrid/BaseGrid.tsx
  packages/@essence/essence-constructor-classes/src/Panel/components/PanelForm/PanelForm.tsx
Labels: enhancement

#583 fix combo and master check
  packages/@essence/essence-constructor-classes/src/FieldCombo/components/FieldComboInput.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/containers/FieldComboContainer.tsx
  packages/@essence/essence-constructor-classes/src/FieldCombo/store/FieldComboModel.ts
  packages/@essence/essence-constructor-classes/src/FieldTable/stores/FieldTableModel/FieldTableModel.ts
  packages/@essence/essence-constructor-classes/src/Filter/store/FilterModel.ts
  packages/@essence/essence-constructor-classes/src/FormPanel/store/FormPanelModel.ts
  packages/@essence/essence-constructor-share/src/Form/useField.ts
  packages/@essence/essence-constructor-share/src/models/RecordsModel/RecordsModel.ts
Labels: bug
